# Generated by Django 5.1.2 on 2025-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
