# Generated by Django 5.1.2 on 2025-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_favoriteproduct_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='products',
            field=models.ManyToManyField(related_name='tags', to='products.product'),
        ),
    ]
